spring:
  config:
    import: classpath:api-keys.yml
  profiles:
    default: dev
  datasource:
    url: jdbc:mysql://localhost:3306/TALKANDPAY?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
  redis:
    host: localhost
    port: 6379
sens:
  service-id: ${api-keys.sens.service-id}
  access-key: ${api-keys.sens.access-key}
  secret-key: ${api-keys.sens.secret-key}
  sender-phone: ${api-keys.sens.sender-phone}
  url: https://sens.apigw.ntruss.com
openapi:
  client-id: ${api-keys.openapi.client-id}
  client-secret: ${api-keys.openapi.client-secret}
  url: https://testapi.openbanking.or.kr
  institution-code: ${api-keys.openapi.institution-code}