### 1. 타행 계좌 등록
POST http://localhost:8080/accounts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json
{
  "bank_code": "090",
  "account_number": "3333037898989",
  "account_name": "카뱅카뱅",
  "auto_debit_agree": "Y",
  "user_id": "1"
}

### 2. 타행 계좌에서 지갑 충전
POST http://localhost:8080/accounts/deposit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json

{
  "account_id" : 9,
  "deposit_money": 100
}