### 1. 당행 송금하기 (송신)
POST http://localhost:8080/transfers HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json

{
  "sender_id"   : 2,
  "receiver_id" : 27,
  "amount"      : 200
}

### 2. 당행 송금하기 (수신)
POST http://localhost:8080/transfers/38e128ae-7589-4033-bddd-0e15527f4be3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0

### 3. 타행 송금하기 (타 계좌 송신)
POST http://localhost:8080/transfers/interbank HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json

{
  "sender_id"   : 1,
  "bank_code" : "092",
  "account_number": "123412341234",
  "amount"      : 100
}

### 4. 타행 송금하기 (등록 자기 계좌 송신)
POST http://localhost:8080/transfers/registered HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json

{
  "sender_id"   : 1,
  "sender_bank_account" : 1,
  "amount"      : 100
}

### 5. 송금 대기 건 확인
GET http://localhost:8080/transfers/pending/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0


### 6.1 송금 이전 (단일 건)
POST http://localhost:8080/transfers/change HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json

{

  "uuid": "c93d9996-7057-4e15-a601-7b4cf10b6e15",
  "request_user_id": "3",
  "change_type": "master"

}

### 6.2 송금 취소 (단일 건)
POST http://localhost:8080/transfers/change HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZXMiOiJBRE1JTiIsImlhdCI6MTY4ODM4ODg2MiwiZXhwIjoxNjg4MzkyNDYyfQ.OXHdLs2BrrAUWpg1gcXxMMubyy234AY8mjqPYY2zVy0
Content-Type: application/json

{
  
  "uuid": "2e87d422-7143-4198-b95d-b15897afafa6",
  "request_user_id": "3",
  "change_type": "cancel"
 
}